language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
branches:
  only:
    - develop
install:
  - "pip install -r requirements.txt"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls check-manifest flake8; fi"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run --source=pathlib2 `type -p pytest`; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then nosetests; fi"
after_success:
  - "pushd test"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi"
  - "popd"
