environment:

  matrix:
    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python35"

    - PYTHON: "C:\\Python36"

    - PYTHON: "C:\\Python37"

init:
  - "%PYTHON%/python --version"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  - "%PYTHON%/Scripts/coverage run -m pytest"

after_test:
  - "%PYTHON%/Scripts/codecov"
