image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"

init:
  - "%PYTHON%/python --version"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  - "%PYTHON%/Scripts/coverage run -m pytest"

after_test:
  - "%PYTHON%/Scripts/codecov"
